kind: Application
spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
  jwt:
    secret: ${SECRET}
    accessTokenExpiration: 300      # 5m
    refreshTokenExpiration: 648000  # 7d
server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-alias: springboot
    key-store-password: password
  error:
    include-message: always
